name: wf_update

on:
  repository_dispatch:
    types: [remove, append]

permissions:
  contents: write
  
jobs:
  build:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
          
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      - name: Update data
        run: python3 update.py ${{ github.event.client_payload.message }}

      - name: Commit to the repo
        run: |
          git config --global user.name "<name>"
          git config --global user.email "<email>"
          git add .
          git commit -m 'update data' || true
          git push
